#!/bin/bash

commit_msg=$(cat $1)
hooks_dir=$(git rev-parse --git-path hooks)

# Configure the sound effect for each semantic commit tag
declare -A sounds
sounds["feat"]="$hooks_dir/sound-effects/tada-military.wav"
sounds["fix"]="$hooks_dir/sound-effects/warzone-headshot.wav"
sounds["refactor"]="$hooks_dir/sound-effects/angel-choir-ahhhh.wav"
sounds["test"]="$hooks_dir/sound-effects/ding.wav"
sounds["docs"]="$hooks_dir/sound-effects/paper.wav"
sounds["perf"]="$hooks_dir/sound-effects/mustang.wav"
sounds["style"]="$hooks_dir/sound-effects/oh-yeah.wav"

function play_sound() {
  if [ -f "$1" ]; then
    powershell.exe -c "(New-Object Media.SoundPlayer '$1').PlaySync()" &
  else
    echo "🔇 Error: Sound file not found!"
    return 1
  fi
}

# Check if commit message starts with each tag
for tag in "${!sounds[@]}"; do
  if [[ $commit_msg =~ ^$tag ]]; then
    play_sound ${sounds[$tag]}
    break
  fi
done

# Proceed with the commit message regardless
exit 0
